/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) burning_zone_impl_dae_fun_jac_x_xdot_u_z_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {15, 1, 1};
static const casadi_int casadi_s1[3] = {1, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[3] = {7, 1, 1};
static const casadi_int casadi_s5[73] = 
  {15, 15, 0, 4, 9, 13, 17, 20,
  24, 29, 33, 37, 40, 43, 46, 49,
  52, 55, 0, 1, 5, 10, 0, 1,
  2, 6, 11, 2, 3, 7, 12, 3,
  4, 8, 13, 4, 9, 14, 0, 5,
  6, 10, 1, 5, 6, 7, 11, 2,
  7, 8, 12, 3, 8, 9, 13, 4,
  9, 14, 0, 5, 10, 1, 6, 11,
  2, 7, 12, 3, 8, 13, 4, 9,
  14};
static const casadi_int casadi_s6[33] = 
  {15, 15, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 11, 12, 13,
  14, 15, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 11, 12, 13,
  14};
static const casadi_int casadi_s7[9] = 
  {15, 1, 0, 5, 0, 1, 2, 3,
  4};
static const casadi_int casadi_s8[3] = {15, 0, 1};

/* burning_zone_impl_dae_fun_jac_x_xdot_u_z:(i0[15],i1[15],i2,i3[0],i4[],i5[7])->(o0[15],o1[15x15,55nz],o2[15x15,15nz],o3[15x1,5nz],o4[15x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28;
  a00=arg[1]? arg[1][0] : 0;
  a01=-1.3999999999999999e+00;
  a02=arg[0]? arg[0][1] : 0;
  a03=arg[0]? arg[0][0] : 0;
  a04=(a02-a03);
  a05=12.;
  a04=(a04/a05);
  a04=(a01*a04);
  a06=1000.;
  a07=arg[2]? arg[2][0] : 0;
  a06=(a06*a07);
  a07=3600.;
  a06=(a06/a07);
  a07=32000000.;
  a08=arg[5]? arg[5][1] : 0;
  a09=arg[5]? arg[5][2] : 0;
  a10=(a08+a09);
  a11=arg[5]? arg[5][3] : 0;
  a10=(a10+a11);
  a12=arg[5]? arg[5][4] : 0;
  a10=(a10+a12);
  a13=1.0000000000000001e-09;
  a10=(a10+a13);
  a08=(a08/a10);
  a07=(a07*a08);
  a08=18000000.;
  a09=(a09/a10);
  a08=(a08*a09);
  a07=(a07+a08);
  a08=20000000.;
  a11=(a11/a10);
  a08=(a08*a11);
  a07=(a07+a08);
  a08=120000000.;
  a12=(a12/a10);
  a08=(a08*a12);
  a07=(a07+a08);
  a06=(a06*a07);
  a08=arg[5]? arg[5][0] : 0;
  a12=3.5000000000000000e+00;
  a08=(a08-a12);
  a08=casadi_sq(a08);
  a12=25.;
  a08=(a08/a12);
  a08=(-a08);
  a08=exp(a08);
  a06=(a06*a08);
  a12=8.3126541614085920e+02;
  a06=(a06/a12);
  a10=5.0000000000000003e-02;
  a11=arg[5]? arg[5][5] : 0;
  a11=(a11/a12);
  a10=(a10*a11);
  a06=(a06-a10);
  a10=1.2071428571428571e+03;
  a11=arg[0]? arg[0][5] : 0;
  a12=(a03-a11);
  a12=(a10*a12);
  a09=1.6625308322797184e+02;
  a12=(a12/a09);
  a13=(a06-a12);
  a14=6.5973445725385654e+03;
  a15=arg[0]? arg[0][10] : 0;
  a03=(a03-a15);
  a03=(a14*a03);
  a03=(a03/a09);
  a13=(a13-a03);
  a16=7.8388328741988714e+05;
  a13=(a13/a16);
  a13=(a04+a13);
  a00=(a00-a13);
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[1]? arg[1][1] : 0;
  a13=arg[0]? arg[0][6] : 0;
  a17=(a02-a13);
  a17=(a10*a17);
  a17=(a17/a09);
  a18=(a06-a17);
  a19=arg[0]? arg[0][11] : 0;
  a20=(a02-a19);
  a20=(a14*a20);
  a20=(a20/a09);
  a18=(a18-a20);
  a18=(a18/a16);
  a04=(a04+a18);
  a00=(a00-a04);
  if (res[0]!=0) res[0][1]=a00;
  a00=arg[1]? arg[1][2] : 0;
  a04=arg[0]? arg[0][2] : 0;
  a02=(a04-a02);
  a02=(a02/a05);
  a02=(a01*a02);
  a18=arg[0]? arg[0][7] : 0;
  a21=(a04-a18);
  a21=(a10*a21);
  a21=(a21/a09);
  a22=(a06-a21);
  a23=arg[0]? arg[0][12] : 0;
  a24=(a04-a23);
  a24=(a14*a24);
  a24=(a24/a09);
  a22=(a22-a24);
  a22=(a22/a16);
  a02=(a02+a22);
  a00=(a00-a02);
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[1]? arg[1][3] : 0;
  a02=arg[0]? arg[0][3] : 0;
  a04=(a02-a04);
  a04=(a04/a05);
  a04=(a01*a04);
  a22=arg[0]? arg[0][8] : 0;
  a25=(a02-a22);
  a25=(a10*a25);
  a25=(a25/a09);
  a26=(a06-a25);
  a27=arg[0]? arg[0][13] : 0;
  a28=(a02-a27);
  a28=(a14*a28);
  a28=(a28/a09);
  a26=(a26-a28);
  a26=(a26/a16);
  a04=(a04+a26);
  a00=(a00-a04);
  if (res[0]!=0) res[0][3]=a00;
  a00=arg[1]? arg[1][4] : 0;
  a04=arg[0]? arg[0][4] : 0;
  a02=(a04-a02);
  a02=(a02/a05);
  a01=(a01*a02);
  a02=arg[0]? arg[0][9] : 0;
  a26=(a04-a02);
  a10=(a10*a26);
  a10=(a10/a09);
  a06=(a06-a10);
  a26=arg[0]? arg[0][14] : 0;
  a04=(a04-a26);
  a14=(a14*a04);
  a14=(a14/a09);
  a06=(a06-a14);
  a06=(a06/a16);
  a01=(a01+a06);
  a00=(a00-a01);
  if (res[0]!=0) res[0][4]=a00;
  a00=arg[1]? arg[1][5] : 0;
  a01=-5.0000000000000001e-03;
  a06=(a13-a11);
  a06=(a06/a05);
  a06=(a01*a06);
  a16=1.6714285714285714e+02;
  a11=(a11-a15);
  a11=(a16*a11);
  a11=(a11/a09);
  a12=(a12-a11);
  a04=9350.;
  a12=(a12/a04);
  a12=(a06+a12);
  a00=(a00-a12);
  if (res[0]!=0) res[0][5]=a00;
  a00=arg[1]? arg[1][6] : 0;
  a12=(a13-a19);
  a12=(a16*a12);
  a12=(a12/a09);
  a17=(a17-a12);
  a17=(a17/a04);
  a06=(a06+a17);
  a00=(a00-a06);
  if (res[0]!=0) res[0][6]=a00;
  a00=arg[1]? arg[1][7] : 0;
  a13=(a18-a13);
  a13=(a13/a05);
  a13=(a01*a13);
  a06=(a18-a23);
  a06=(a16*a06);
  a06=(a06/a09);
  a21=(a21-a06);
  a21=(a21/a04);
  a13=(a13+a21);
  a00=(a00-a13);
  if (res[0]!=0) res[0][7]=a00;
  a00=arg[1]? arg[1][8] : 0;
  a18=(a22-a18);
  a18=(a18/a05);
  a18=(a01*a18);
  a13=(a22-a27);
  a13=(a16*a13);
  a13=(a13/a09);
  a25=(a25-a13);
  a25=(a25/a04);
  a18=(a18+a25);
  a00=(a00-a18);
  if (res[0]!=0) res[0][8]=a00;
  a00=arg[1]? arg[1][9] : 0;
  a22=(a02-a22);
  a22=(a22/a05);
  a01=(a01*a22);
  a02=(a02-a26);
  a16=(a16*a02);
  a16=(a16/a09);
  a10=(a10-a16);
  a10=(a10/a04);
  a01=(a01+a10);
  a00=(a00-a01);
  if (res[0]!=0) res[0][9]=a00;
  a00=arg[1]? arg[1][10] : 0;
  a03=(a03+a11);
  a11=1.9000352368911070e+04;
  a01=300.;
  a15=(a15-a01);
  a15=(a11*a15);
  a10=1.6625308322897183e+02;
  a15=(a15/a10);
  a03=(a03-a15);
  a15=2.3750440461138836e+08;
  a03=(a03/a15);
  a00=(a00-a03);
  if (res[0]!=0) res[0][10]=a00;
  a00=arg[1]? arg[1][11] : 0;
  a20=(a20+a12);
  a19=(a19-a01);
  a19=(a11*a19);
  a19=(a19/a10);
  a20=(a20-a19);
  a20=(a20/a15);
  a00=(a00-a20);
  if (res[0]!=0) res[0][11]=a00;
  a00=arg[1]? arg[1][12] : 0;
  a24=(a24+a06);
  a23=(a23-a01);
  a23=(a11*a23);
  a23=(a23/a10);
  a24=(a24-a23);
  a24=(a24/a15);
  a00=(a00-a24);
  if (res[0]!=0) res[0][12]=a00;
  a00=arg[1]? arg[1][13] : 0;
  a28=(a28+a13);
  a27=(a27-a01);
  a27=(a11*a27);
  a27=(a27/a10);
  a28=(a28-a27);
  a28=(a28/a15);
  a00=(a00-a28);
  if (res[0]!=0) res[0][13]=a00;
  a00=arg[1]? arg[1][14] : 0;
  a14=(a14+a16);
  a26=(a26-a01);
  a11=(a11*a26);
  a11=(a11/a10);
  a14=(a14-a11);
  a14=(a14/a15);
  a00=(a00-a14);
  if (res[0]!=0) res[0][14]=a00;
  a00=-1.1660678094714094e-01;
  if (res[1]!=0) res[1][0]=a00;
  a00=-1.1666666666666665e-01;
  if (res[1]!=0) res[1][1]=a00;
  a14=-7.7656417206219608e-04;
  if (res[1]!=0) res[1][2]=a14;
  a15=-1.6708127896604448e-07;
  if (res[1]!=0) res[1][3]=a15;
  a11=1.1666666666666665e-01;
  if (res[1]!=0) res[1][4]=a11;
  a11=1.1672655238619237e-01;
  if (res[1]!=0) res[1][5]=a11;
  if (res[1]!=0) res[1][6]=a00;
  if (res[1]!=0) res[1][7]=a14;
  if (res[1]!=0) res[1][8]=a15;
  if (res[1]!=0) res[1][9]=a11;
  if (res[1]!=0) res[1][10]=a00;
  if (res[1]!=0) res[1][11]=a14;
  if (res[1]!=0) res[1][12]=a15;
  if (res[1]!=0) res[1][13]=a11;
  if (res[1]!=0) res[1][14]=a00;
  if (res[1]!=0) res[1][15]=a14;
  if (res[1]!=0) res[1][16]=a15;
  if (res[1]!=0) res[1][17]=a11;
  if (res[1]!=0) res[1][18]=a14;
  if (res[1]!=0) res[1][19]=a15;
  a15=-9.2626990845542110e-06;
  if (res[1]!=0) res[1][20]=a15;
  a14=4.6742177537337204e-04;
  if (res[1]!=0) res[1][21]=a14;
  a14=-4.1666666666666664e-04;
  if (res[1]!=0) res[1][22]=a14;
  a11=-4.2329822301098539e-09;
  if (res[1]!=0) res[1][23]=a11;
  if (res[1]!=0) res[1][24]=a15;
  a00=4.1666666666666664e-04;
  if (res[1]!=0) res[1][25]=a00;
  a00=1.3007551087067053e-03;
  if (res[1]!=0) res[1][26]=a00;
  if (res[1]!=0) res[1][27]=a14;
  if (res[1]!=0) res[1][28]=a11;
  if (res[1]!=0) res[1][29]=a15;
  if (res[1]!=0) res[1][30]=a00;
  if (res[1]!=0) res[1][31]=a14;
  if (res[1]!=0) res[1][32]=a11;
  if (res[1]!=0) res[1][33]=a15;
  if (res[1]!=0) res[1][34]=a00;
  if (res[1]!=0) res[1][35]=a14;
  if (res[1]!=0) res[1][36]=a11;
  if (res[1]!=0) res[1][37]=a15;
  if (res[1]!=0) res[1][38]=a00;
  if (res[1]!=0) res[1][39]=a11;
  a11=-5.0623020441158768e-05;
  if (res[1]!=0) res[1][40]=a11;
  a00=-1.0752426997784253e-04;
  if (res[1]!=0) res[1][41]=a00;
  a15=6.5250834461546821e-07;
  if (res[1]!=0) res[1][42]=a15;
  if (res[1]!=0) res[1][43]=a11;
  if (res[1]!=0) res[1][44]=a00;
  if (res[1]!=0) res[1][45]=a15;
  if (res[1]!=0) res[1][46]=a11;
  if (res[1]!=0) res[1][47]=a00;
  if (res[1]!=0) res[1][48]=a15;
  if (res[1]!=0) res[1][49]=a11;
  if (res[1]!=0) res[1][50]=a00;
  if (res[1]!=0) res[1][51]=a15;
  if (res[1]!=0) res[1][52]=a11;
  if (res[1]!=0) res[1][53]=a00;
  if (res[1]!=0) res[1][54]=a15;
  a15=1.;
  if (res[2]!=0) res[2][0]=a15;
  if (res[2]!=0) res[2][1]=a15;
  if (res[2]!=0) res[2][2]=a15;
  if (res[2]!=0) res[2][3]=a15;
  if (res[2]!=0) res[2][4]=a15;
  if (res[2]!=0) res[2][5]=a15;
  if (res[2]!=0) res[2][6]=a15;
  if (res[2]!=0) res[2][7]=a15;
  if (res[2]!=0) res[2][8]=a15;
  if (res[2]!=0) res[2][9]=a15;
  if (res[2]!=0) res[2][10]=a15;
  if (res[2]!=0) res[2][11]=a15;
  if (res[2]!=0) res[2][12]=a15;
  if (res[2]!=0) res[2][13]=a15;
  if (res[2]!=0) res[2][14]=a15;
  a15=1.2757001151172010e-06;
  a00=1.2029852085540733e-03;
  a11=2.7777777777777779e-01;
  a11=(a11*a07);
  a08=(a08*a11);
  a00=(a00*a08);
  a15=(a15*a00);
  a15=(-a15);
  if (res[3]!=0) res[3][0]=a15;
  if (res[3]!=0) res[3][1]=a15;
  if (res[3]!=0) res[3][2]=a15;
  if (res[3]!=0) res[3][3]=a15;
  if (res[3]!=0) res[3][4]=a15;
  return 0;
}

CASADI_SYMBOL_EXPORT int burning_zone_impl_dae_fun_jac_x_xdot_u_z(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int burning_zone_impl_dae_fun_jac_x_xdot_u_z_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int burning_zone_impl_dae_fun_jac_x_xdot_u_z_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void burning_zone_impl_dae_fun_jac_x_xdot_u_z_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int burning_zone_impl_dae_fun_jac_x_xdot_u_z_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void burning_zone_impl_dae_fun_jac_x_xdot_u_z_release(int mem) {
}

CASADI_SYMBOL_EXPORT void burning_zone_impl_dae_fun_jac_x_xdot_u_z_incref(void) {
}

CASADI_SYMBOL_EXPORT void burning_zone_impl_dae_fun_jac_x_xdot_u_z_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int burning_zone_impl_dae_fun_jac_x_xdot_u_z_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int burning_zone_impl_dae_fun_jac_x_xdot_u_z_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real burning_zone_impl_dae_fun_jac_x_xdot_u_z_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* burning_zone_impl_dae_fun_jac_x_xdot_u_z_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* burning_zone_impl_dae_fun_jac_x_xdot_u_z_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* burning_zone_impl_dae_fun_jac_x_xdot_u_z_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    case 5: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* burning_zone_impl_dae_fun_jac_x_xdot_u_z_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    case 3: return casadi_s7;
    case 4: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int burning_zone_impl_dae_fun_jac_x_xdot_u_z_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int burning_zone_impl_dae_fun_jac_x_xdot_u_z_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
