/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) burning_zone_impl_dae_jac_x_xdot_u_z_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

static const casadi_int casadi_s0[3] = {15, 1, 1};
static const casadi_int casadi_s1[3] = {1, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[3] = {4, 1, 1};
static const casadi_int casadi_s5[73] = 
  {15, 15, 0, 4, 9, 13, 17, 20,
  24, 29, 33, 37, 40, 43, 46, 49,
  52, 55, 0, 1, 5, 10, 0, 1,
  2, 6, 11, 2, 3, 7, 12, 3,
  4, 8, 13, 4, 9, 14, 0, 5,
  6, 10, 1, 5, 6, 7, 11, 2,
  7, 8, 12, 3, 8, 9, 13, 4,
  9, 14, 0, 5, 10, 1, 6, 11,
  2, 7, 12, 3, 8, 13, 4, 9,
  14};
static const casadi_int casadi_s6[33] = 
  {15, 15, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 11, 12, 13,
  14, 15, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 11, 12, 13,
  14};
static const casadi_int casadi_s7[9] = 
  {15, 1, 0, 5, 0, 1, 2, 3,
  4};
static const casadi_int casadi_s8[3] = {15, 0, 1};

/* burning_zone_impl_dae_jac_x_xdot_u_z:(i0[15],i1[15],i2,i3[0],i4[],i5[4])->(o0[15x15,55nz],o1[15x15,15nz],o2[15x1,5nz],o3[15x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=-1.1660678094714094e-01;
  if (res[0]!=0) res[0][0]=a0;
  a0=-1.1666666666666665e-01;
  if (res[0]!=0) res[0][1]=a0;
  a1=-7.7656417206219608e-04;
  if (res[0]!=0) res[0][2]=a1;
  a2=-1.6708127896604448e-07;
  if (res[0]!=0) res[0][3]=a2;
  a3=1.1666666666666665e-01;
  if (res[0]!=0) res[0][4]=a3;
  a3=1.1672655238619237e-01;
  if (res[0]!=0) res[0][5]=a3;
  if (res[0]!=0) res[0][6]=a0;
  if (res[0]!=0) res[0][7]=a1;
  if (res[0]!=0) res[0][8]=a2;
  if (res[0]!=0) res[0][9]=a3;
  if (res[0]!=0) res[0][10]=a0;
  if (res[0]!=0) res[0][11]=a1;
  if (res[0]!=0) res[0][12]=a2;
  if (res[0]!=0) res[0][13]=a3;
  if (res[0]!=0) res[0][14]=a0;
  if (res[0]!=0) res[0][15]=a1;
  if (res[0]!=0) res[0][16]=a2;
  if (res[0]!=0) res[0][17]=a3;
  if (res[0]!=0) res[0][18]=a1;
  if (res[0]!=0) res[0][19]=a2;
  a2=-9.2626990845542110e-06;
  if (res[0]!=0) res[0][20]=a2;
  a1=4.6742177537337204e-04;
  if (res[0]!=0) res[0][21]=a1;
  a1=-4.1666666666666664e-04;
  if (res[0]!=0) res[0][22]=a1;
  a3=-4.2329822301098539e-09;
  if (res[0]!=0) res[0][23]=a3;
  if (res[0]!=0) res[0][24]=a2;
  a0=4.1666666666666664e-04;
  if (res[0]!=0) res[0][25]=a0;
  a0=1.3007551087067053e-03;
  if (res[0]!=0) res[0][26]=a0;
  if (res[0]!=0) res[0][27]=a1;
  if (res[0]!=0) res[0][28]=a3;
  if (res[0]!=0) res[0][29]=a2;
  if (res[0]!=0) res[0][30]=a0;
  if (res[0]!=0) res[0][31]=a1;
  if (res[0]!=0) res[0][32]=a3;
  if (res[0]!=0) res[0][33]=a2;
  if (res[0]!=0) res[0][34]=a0;
  if (res[0]!=0) res[0][35]=a1;
  if (res[0]!=0) res[0][36]=a3;
  if (res[0]!=0) res[0][37]=a2;
  if (res[0]!=0) res[0][38]=a0;
  if (res[0]!=0) res[0][39]=a3;
  a3=-5.0623020441158768e-05;
  if (res[0]!=0) res[0][40]=a3;
  a0=-1.0752426997784253e-04;
  if (res[0]!=0) res[0][41]=a0;
  a2=6.5250834461546821e-07;
  if (res[0]!=0) res[0][42]=a2;
  if (res[0]!=0) res[0][43]=a3;
  if (res[0]!=0) res[0][44]=a0;
  if (res[0]!=0) res[0][45]=a2;
  if (res[0]!=0) res[0][46]=a3;
  if (res[0]!=0) res[0][47]=a0;
  if (res[0]!=0) res[0][48]=a2;
  if (res[0]!=0) res[0][49]=a3;
  if (res[0]!=0) res[0][50]=a0;
  if (res[0]!=0) res[0][51]=a2;
  if (res[0]!=0) res[0][52]=a3;
  if (res[0]!=0) res[0][53]=a0;
  if (res[0]!=0) res[0][54]=a2;
  a2=1.;
  if (res[1]!=0) res[1][0]=a2;
  if (res[1]!=0) res[1][1]=a2;
  if (res[1]!=0) res[1][2]=a2;
  if (res[1]!=0) res[1][3]=a2;
  if (res[1]!=0) res[1][4]=a2;
  if (res[1]!=0) res[1][5]=a2;
  if (res[1]!=0) res[1][6]=a2;
  if (res[1]!=0) res[1][7]=a2;
  if (res[1]!=0) res[1][8]=a2;
  if (res[1]!=0) res[1][9]=a2;
  if (res[1]!=0) res[1][10]=a2;
  if (res[1]!=0) res[1][11]=a2;
  if (res[1]!=0) res[1][12]=a2;
  if (res[1]!=0) res[1][13]=a2;
  if (res[1]!=0) res[1][14]=a2;
  a0=1.2757001151172010e-06;
  a3=1.2029852085540733e-03;
  a1=arg[5]? arg[5][0] : 0;
  a4=3.5000000000000000e+00;
  a1=(a1-a4);
  a1=casadi_sq(a1);
  a4=25.;
  a1=(a1/a4);
  a1=(-a1);
  a1=exp(a1);
  a4=2.7777777777777779e-01;
  a5=32000000.;
  a6=arg[5]? arg[5][1] : 0;
  a7=arg[5]? arg[5][2] : 0;
  a8=(a6+a7);
  a2=(a2-a6);
  a2=(a2-a7);
  a9=0.;
  a2=casadi_fmax(a2,a9);
  a8=(a8+a2);
  a9=1.0000000000000001e-09;
  a8=(a8+a9);
  a6=(a6/a8);
  a5=(a5*a6);
  a6=18000000.;
  a2=(a2/a8);
  a6=(a6*a2);
  a5=(a5+a6);
  a6=20000000.;
  a7=(a7/a8);
  a6=(a6*a7);
  a5=(a5+a6);
  a4=(a4*a5);
  a1=(a1*a4);
  a3=(a3*a1);
  a0=(a0*a3);
  a0=(-a0);
  if (res[2]!=0) res[2][0]=a0;
  if (res[2]!=0) res[2][1]=a0;
  if (res[2]!=0) res[2][2]=a0;
  if (res[2]!=0) res[2][3]=a0;
  if (res[2]!=0) res[2][4]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int burning_zone_impl_dae_jac_x_xdot_u_z(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int burning_zone_impl_dae_jac_x_xdot_u_z_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int burning_zone_impl_dae_jac_x_xdot_u_z_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void burning_zone_impl_dae_jac_x_xdot_u_z_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int burning_zone_impl_dae_jac_x_xdot_u_z_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void burning_zone_impl_dae_jac_x_xdot_u_z_release(int mem) {
}

CASADI_SYMBOL_EXPORT void burning_zone_impl_dae_jac_x_xdot_u_z_incref(void) {
}

CASADI_SYMBOL_EXPORT void burning_zone_impl_dae_jac_x_xdot_u_z_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int burning_zone_impl_dae_jac_x_xdot_u_z_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int burning_zone_impl_dae_jac_x_xdot_u_z_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real burning_zone_impl_dae_jac_x_xdot_u_z_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* burning_zone_impl_dae_jac_x_xdot_u_z_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* burning_zone_impl_dae_jac_x_xdot_u_z_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* burning_zone_impl_dae_jac_x_xdot_u_z_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    case 5: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* burning_zone_impl_dae_jac_x_xdot_u_z_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    case 2: return casadi_s7;
    case 3: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int burning_zone_impl_dae_jac_x_xdot_u_z_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int burning_zone_impl_dae_jac_x_xdot_u_z_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 4*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
